package domain;

public enum TerritoryName {
    ALASKA, NORTHWEST_TERRITORY, GREENLAND, ALBERTA, ONTARIO, QUEBEC,
    WESTERN_UNITED_STATES, EASTERN_UNITED_STATES, CENTRAL_AMERICA,
    VENEZUELA, PERU, BRAZIL, ARGENTINA,
    ICELAND, GREAT_BRITAIN, WESTERN_EUROPE, NORTHERN_EUROPE,
    SOUTHERN_EUROPE, SCANDINAVIA, UKRAINE,
    NORTH_AFRICA, EGYPT, EAST_AFRICA, CONGO, SOUTH_AFRICA, MADAGASCAR,
    MIDDLE_EAST, AFGHANISTAN, URAL, SIBERIA, YAKUTSK, KAMCHATKA,
    IRKUTSK, MONGOLIA, JAPAN, CHINA, INDIA, SIAM,
    EASTERN_AUSTRALIA, WESTERN_AUSTRALIA, NEW_GUINEA, INDONESIA
}